### PR TITLE
Add Monster: 2k Hornet

### PR DESCRIPTION
**Pull request by carstene1ns**
Open Question is: "How to handle monsters in 2k vs. 2k3 battle?" - Problem is they look left in 2k and right in 2k3.

### CODE REVIEW

**Comment by fdelapena** [comment]
> Open Question is: "How to handle monsters in 2k vs. 2k3 battle?" - Problem is they look left in 2k and right in 2k3.

IMO, 3/4 poses fit usually for both battle styles.

Regarding the wasp, it might fit by horizontal flip to head actors by default.

**Comment by carstene1ns** [comment]
> Regarding the wasp, it might fit by horizontal flip to head actors by default.

Is not about the wasp, __all__ Monsters look in the same direction.

**Comment by fdelapena** [comment]
I guess nobody will note that difference (hopefully). Flipping assets programmatically which are known to face left looks pretty dirty and having dupe assets does not look a good idea IMO.

So I'd vote for add all assets facing right for our RTP until some nitpicky 2k user complains (assets will be different already, so...).

**Comment by Ghabry** [comment]
I'm also in favor of "mirror them to look to the right" otherwise they won't work in 2k3 battles.

Most of the 2k-monsters are screen-facing.

**Comment by fdelapena** [comment]
Superseded by #29.

**Pull request closed without merging**
