### PR TITLE
Adding some RTP files

### PR DESCRIPTION
**Pull request by Someoneman**
I made 3 battle animations and 1 midi track. All CC0.

### CODE REVIEW

**Comment by Ghabry** [comment]
Thank you for your contribution.

The battle animations do not look like simple repaints, so imo they are fine to add this way (the animations are so simple, is hard to  :)

Though have a change request for the arrow:

- Can you make it a bit longer in both directions? Compared to the "real" RTP arrow it is quite short.
- Take a look at Cell 3 of the original file. Here the chopped off arrow is 5 pixel lower than in the previous frame. I guess this shall simulate some motion and indicate that the arrow in now inside the target. Can you adjust this?

(Also the dimensions of the files are different, but this is something we can easily fix afterwards)

**Review by fdelapena — APPROVED** [review]

**Comment by jetrotal** [comment]
The files must be in a compatible indexed color mode, with the color 0 being the background color.

Fixed the issue, and uploaded it here:
https://github.com/EasyRPG/RTP/pull/34/commits

**Comment by fdelapena** [comment]
Thank you! your files have been added in #34 with the corresponding authors file update.

**Comment by jetrotal** [comment]
feel free to join us on discord, feedback there is a lot faster https://t.co/0MJZlivP9D

**Pull request closed without merging**
