### PR TITLE
A Few Character Sets

### PR DESCRIPTION
**Pull request by AntumDeluge**
- [Slime sprite created by nudelchef (CC0)](https://opengameart.org/node/133246). I scaled it down from 48x64 to 24x32 to fit the RTP.
- [Skeleton sprite by artisticdude & AntumDeluge (CC0)](https://opengameart.org/node/83067).
- [Chicken sprite by Shepardskin & AntumDeluge (CC0)](https://opengameart.org/node/76895).

### CODE REVIEW

**Comment by carstene1ns** [comment]
Much appreciated!

**Comment by AntumDeluge** [comment]
If there are any that you don't like, let me know & I will remove them.

**Comment by Ghabry** [comment]
Thanks. I'm not sure if the skeleton will fit the art style as it is kinda detailed, but havn't tested it in action yet :)

**Review by fdelapena — APPROVED** [review]

**Review by halotroop2288 — APPROVED** [review]

**Comment by jetrotal** [comment]
Hey! Sorry for the delay.


I drew a skelleton using Jason Perry[CC0] Proportions:
EasyChar_2023-02-13T16_40_07 202Z

I'm Also testing a Skelly Mage, using R.C.O's body assets [CC-BY]:
EasyChar_2023-02-13T16_45_03 317Z


I plan on testing the Slime from merchant shade [CC0], since it's closer to our artstyle:
https://merchant-shade.itch.io/16x16-puny-characters
image

The chicken seems fine, it may combine, with Dog and Sheep from tiny Animals by Kacper Woźniak [CC-BY] 
https://thkaspar.itch.io/tth-animals 
image

**Comment by AntumDeluge** [comment]
Nice looking assets. :)

Feel free to close this.

**Comment by jetrotal** [comment]
closing this pr, the changes commented here are under #42

**Pull request closed without merging**
